import random

tweet = [
    "Want to come over and watch porn on my flat screen mirror?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "Your face would look better between my legs.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "I give you permission to wake me up if you get horny.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "When she's had a rough day, give her a rough night.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/coronavirus-and-me-and-dad-erotic-book.html",
    "I wanna be the reason you slightly tilt your phone away from others when you read it.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/mother-in-law-erotic-book-illustrated.html",
    "When it's so good you're shaking.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-crush-erotic-book-illustrated.html",
    "I swear to you I won't stop until your legs are shaking and the neighbors know my name.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/high-school-experimentation-erotic-book.html",
    "You. Me. Bed. Now.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-photo-shoot-erotic-book-illustrated.html",
    "Take her like it's the first time and the last time every single time.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "Save water. Shower together.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "Respect me. Adore me. Dominate me.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/black-cock-whore-erotic-book-illustrated.html",
    "Kiss me a lot. Touch me all over. And lick me in my special spot.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-wife-is-my-fantasy-erotic-book.html",
    "I promise to always be by your side. Or under you. Or on top ...\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/strangers-erotic-book-illustrated.html",
    "Others have sex in the kitchen. I eat in bed.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "Stop undressing me with your eyes! Use your teeth.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/girls-domination-erotic-book-illustrated.html",
    "Stop undressing me with your eyes! Use your teeth.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/babysitter-erotic-book-illustrated.html",
    "Let's have a who's better in bed contest. I'm hoping to be a sore loser.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/gangbang-erotic-book-illustrated.html",
    "It's been a long day. I need one of those hugs that turns into sex.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-wifes-best-friend-erotic-book.html",
    "Some of the best moments in life are the ones you can't tell anyone about.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sons-college-friends-erotic-book.html",
    "Can I have you for breakfast in bed today?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-aunt-erotic-book-illustrated.html",
    "Be naked when I get home.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sex-in-paris-erotic-book-illustrated.html",
    "Blow me.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/soccer-mom-erotic-book-illustrated.html",
    "I'm a lover, not a fighter. Unless you like it rough.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "I want to taste me on your fingers.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "I licked it so it's mine.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/coronavirus-and-me-and-dad-erotic-book.html",
    "Your lips are like wine and I want to get drunk!\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/mother-in-law-erotic-book-illustrated.html",
    "Go ahead. Touch it.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-crush-erotic-book-illustrated.html",
    "Excuse me for being too forward, but your lips make me wonder what the rest of you would taste like ...\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/high-school-experimentation-erotic-book.html",
    "Now spread your legs and try to tell me about your day.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-photo-shoot-erotic-book-illustrated.html",
    "Spank me. It's the only way I learn.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "The best things in life make you sweaty.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "I need you and I want you. Butt naked. In my bed. Right now.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/black-cock-whore-erotic-book-illustrated.html",
    "Your pants, they bother me. Take them off!\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-wife-is-my-fantasy-erotic-book.html",
    "I want you, all of you. I want to feel you inside me, deep inside me.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/strangers-erotic-book-illustrated.html",
    "I want you to tell me when you’re going to cum, hear you moan my name and fuck me harder.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "Kiss me hard & fuck me harder!\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/girls-domination-erotic-book-illustrated.html",
    "WE SHOULD FUCK.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/babysitter-erotic-book-illustrated.html",
    "Like right now, right here. Hard, fast.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/gangbang-erotic-book-illustrated.html",
    "Pin me down, kiss me hard, look me in the eyes and fuck me like you’ve never fucked someone before.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-wifes-best-friend-erotic-book.html",
    "Moanday. Tongueday. Wetday. Thirstday. Freakday. Sexday. Suckday.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sons-college-friends-erotic-book.html",
    "Your face would look better between my legs.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-aunt-erotic-book-illustrated.html",
    "I swear to God I won’t stop until you’re shaking.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sex-in-paris-erotic-book-illustrated.html",
    "Get your ass in my bed\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/soccer-mom-erotic-book-illustrated.html",
    "Nice pants. Can I test the zipper?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "Tease me until I’m begging for it\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "Your clothes would look nice on my bedroom floor.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/coronavirus-and-me-and-dad-erotic-book.html",
    "Be naked when I come home.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/mother-in-law-erotic-book-illustrated.html",
    "Lets makeout, have sex, cuddle and have a deep talk.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-crush-erotic-book-illustrated.html",
    "Then lets have sex again, go out to eat, then go back home, watch a movie and have sex again.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/high-school-experimentation-erotic-book.html",
    "I wanna do bad things to you\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-photo-shoot-erotic-book-illustrated.html",
    "I swear to you I won’t stop until your legs are shaking and the neighbors know my name.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "I just want you to be happy. And naked.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "I’m a lip bitter\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/black-cock-whore-erotic-book-illustrated.html",
    "I’m in my bed, you’re in yours. One of us is obviously in the wrong place.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-wife-is-my-fantasy-erotic-book.html",
    "We should have lots of sex\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/strangers-erotic-book-illustrated.html",
    "I love the way you fuck me\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "I licked it, so it’s mine!\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/girls-domination-erotic-book-illustrated.html",
    "If you bite my pis or kiss my neck, I promise to rip your fucking clothes off.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/babysitter-erotic-book-illustrated.html",
    "Shut up and kiss me.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/gangbang-erotic-book-illustrated.html",
    "Be gentle with me\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-wifes-best-friend-erotic-book.html",
    "Be sweet ad kind, oh hell! Who am I kidding? Flip me over, ride my ass and pull my hair!\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sons-college-friends-erotic-book.html",
    "Go ahead. Touch it\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-aunt-erotic-book-illustrated.html",
    "I want to capture you, like this, and freeze it forever.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sex-in-paris-erotic-book-illustrated.html",
    "Eyes on me, baby. Always on me!\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/soccer-mom-erotic-book-illustrated.html",
    "I want you inside me\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "Spank me. It’s the only way I learn\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "Push me up against the wall and do dirty things to me.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/coronavirus-and-me-and-dad-erotic-book.html",
    "It’s not that I’m horny all the time.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/mother-in-law-erotic-book-illustrated.html",
    "No woman gets an orgasm from shining the kitchen floor\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-crush-erotic-book-illustrated.html",
    "I don’t know the question, but sex is definitely the answer.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/high-school-experimentation-erotic-book.html",
    "Everything in the world is about sex except sex. Sex is about power.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-photo-shoot-erotic-book-illustrated.html",
    "Good sex is like good bridge. If you don’t have a good partner, you’d better have a good hand.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "The difference between sex and love is that sex relieves tension and love causes it.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "Sex without love is as hollow and ridiculous as love without sex.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/black-cock-whore-erotic-book-illustrated.html",
    "Sex is kicking death in the ass while singing.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-wife-is-my-fantasy-erotic-book.html",
    "Is sex dirty? Only when it’s being done right.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/strangers-erotic-book-illustrated.html",
    "Sex is an emotion in motion.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "Love is the answer, but while you are waiting for the answer, sex raises some pretty good questions.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/girls-domination-erotic-book-illustrated.html",
    "Sex is the most fun you can have without laughing.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/babysitter-erotic-book-illustrated.html",
    "I never realized until lately that women were supposed to be the inferior sex.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/gangbang-erotic-book-illustrated.html",
    "I haven’t had sex in eight months. To be honest, I now prefer to go bowling.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-wifes-best-friend-erotic-book.html",
    "I talk so much about sex that girls just want to meet me.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sons-college-friends-erotic-book.html",
    "Sex is a momentary itch, love never lets you go.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-aunt-erotic-book-illustrated.html",
    "I’ve enjoyed the opposite sex a lot. Always have. Always will.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sex-in-paris-erotic-book-illustrated.html",
    "I need more sex, ok? Before I die I wanna taste everyone in the world.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/soccer-mom-erotic-book-illustrated.html",
    "Software is like sex: it’s better when it’s free.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "I need your cock!\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "Fuck me hard.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/coronavirus-and-me-and-dad-erotic-book.html",
    "Deeper, Deeper, DEEPER!\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/mother-in-law-erotic-book-illustrated.html",
    "Just like that.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-crush-erotic-book-illustrated.html",
    "Don’t stop.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/high-school-experimentation-erotic-book.html",
    "I love being your fuck slut.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-photo-shoot-erotic-book-illustrated.html",
    "I think I’m in love with your dick.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "Holy shit, I’m cumming.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "I want to taste myself on your cock.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/black-cock-whore-erotic-book-illustrated.html",
    "Make me cum baby.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-wife-is-my-fantasy-erotic-book.html",
    "I’m dripping wet.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/strangers-erotic-book-illustrated.html",
    "I’m about to explode.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "Oh-my-fucking-god!\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/girls-domination-erotic-book-illustrated.html",
    "I’ve never been fucked like this before.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/babysitter-erotic-book-illustrated.html",
    "You’re going to make me pass out with pleasure.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/gangbang-erotic-book-illustrated.html",
    "I just wanna be your sex slut.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-wifes-best-friend-erotic-book.html",
    "Grab my hair and fuck me like a dog.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sons-college-friends-erotic-book.html",
    "I want to feel your cum all over my face.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-aunt-erotic-book-illustrated.html",
    "I want to feel you shoot your load in my mouth. \nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sex-in-paris-erotic-book-illustrated.html",
    "I’m going to jerk you off until I get every last drop out of you.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/soccer-mom-erotic-book-illustrated.html",
    "Let’s spend the entire weekend together completely naked!\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "Fuck me, fuck me!\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "Pound me harder!\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/coronavirus-and-me-and-dad-erotic-book.html",
    "FUCK ME LIKE AN ANIMAL\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/mother-in-law-erotic-book-illustrated.html",
    "I love you\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-crush-erotic-book-illustrated.html",
    "You make me feel amazing baby.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/high-school-experimentation-erotic-book.html",
    "I feel tiny in your arms.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-photo-shoot-erotic-book-illustrated.html",
    "That feels so good.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "I can’t believe I met you.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "Please, please, Please, PLEEAAAASSSSEEEEE… \nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/black-cock-whore-erotic-book-illustrated.html",
    "Tonight is all about you.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-wife-is-my-fantasy-erotic-book.html",
    "You like that baby?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/strangers-erotic-book-illustrated.html",
    "Mmmmmm, you taste so good.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "I want you so bad.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/girls-domination-erotic-book-illustrated.html",
    "I love your body \nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/babysitter-erotic-book-illustrated.html",
    "I wish we were at home, so I could do some terrible things to you.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/gangbang-erotic-book-illustrated.html",
    "Why am I always so horny when there are other people around.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-wifes-best-friend-erotic-book.html",
    "I just want to rip your clothes off right now.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sons-college-friends-erotic-book.html",
    "If we weren’t at your friend’s house, I’d be on my knees with you in my mouth.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-aunt-erotic-book-illustrated.html",
    "I can’t believe we decided to go shopping when we could be at home fucking.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sex-in-paris-erotic-book-illustrated.html",
    "I think going to the gym together was a bad idea, all I want to do is fuck you when I see you sweating like that.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/soccer-mom-erotic-book-illustrated.html",
    "If you don’t stop looking at me like that, we’re going to to have to go somewhere private.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "You know I’m not wearing panties?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "I just want you to know I’m dripping wet.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/coronavirus-and-me-and-dad-erotic-book.html",
    "I need you to walk in front of me so I can see your ass.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/mother-in-law-erotic-book-illustrated.html",
    "Don’t look at me like that when we’re here; it’s making me so fucking horny.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-crush-erotic-book-illustrated.html",
    "You look really sexy when you wear that shirt/jeans/top.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/high-school-experimentation-erotic-book.html",
    "It’s so hot when you grab me in public.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-photo-shoot-erotic-book-illustrated.html",
    "I can’t wait to get you home.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "I wore this skirt just for you.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "Do you know how wet I am right now?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/black-cock-whore-erotic-book-illustrated.html",
    "Would it be rude of me to start sucking your dick right now?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-wife-is-my-fantasy-erotic-book.html",
    "I’m just going to rub your leg, let’s see how long it takes you to get hard.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/strangers-erotic-book-illustrated.html",
    "I’m thinking of a number between one and ten. If you can guess it, I’ll give you a blow job.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "Do you want to lie down for a bit?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/girls-domination-erotic-book-illustrated.html",
    "Can you help me with something in the bedroom.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/babysitter-erotic-book-illustrated.html",
    "Now that we’re alone, I need to feel you inside me.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/gangbang-erotic-book-illustrated.html",
    "I need you so bad right now.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-wifes-best-friend-erotic-book.html",
    "Why aren’t you here right now, I’m so fucking horny.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sons-college-friends-erotic-book.html",
    "I can’t concentrate at work. All I can think about is sucking your dick.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-aunt-erotic-book-illustrated.html",
    "My panties are soaked, get home quick.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sex-in-paris-erotic-book-illustrated.html",
    "Last night was incredible. I can’t stop thinking about it.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/soccer-mom-erotic-book-illustrated.html",
    "What do you want me to wear in bed tonight?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/coronavirus-and-me-and-dad-erotic-book.html",
    "I keep fantasizing about what I’m going to do to you later.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/mother-in-law-erotic-book-illustrated.html",
    "I was thinking about you today.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-crush-erotic-book-illustrated.html",
    "I’m going to give you the wettest blowjob tonight.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/high-school-experimentation-erotic-book.html",
    "Do you want to try anal with me?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-photo-shoot-erotic-book-illustrated.html",
    "I love masturbating while talking to you, but what I really need is you, here, fucking me.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "I’m blushing just saying this, but I miss your dick so much.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "I wish I could just clone your dick, so I have something to remind me of you.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/black-cock-whore-erotic-book-illustrated.html",
    "Why can’t we just quit our jobs, live together and fuck all day, every day.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-wife-is-my-fantasy-erotic-book.html",
    "I dreamt about you last night, and it was fantastic, but I woke up, and you weren’t here.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/strangers-erotic-book-illustrated.html",
    "I keep thinking about just quitting school/my job and coming to see you tonight.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "Lie down and shut up.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/girls-domination-erotic-book-illustrated.html",
    "Tonight is all about me.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/babysitter-erotic-book-illustrated.html",
    "Take your clothes off and get into bed.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/gangbang-erotic-book-illustrated.html",
    "On your knees, bitch.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-wifes-best-friend-erotic-book.html",
    "Tonight, I’m going to be inside YOU.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sons-college-friends-erotic-book.html",
    "I want to hear you say my name, say it bitch.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-aunt-erotic-book-illustrated.html",
    "Beg me.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sex-in-paris-erotic-book-illustrated.html",
    "You’re going to get spanked until you cry.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/soccer-mom-erotic-book-illustrated.html",
    "Your wish is my command.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/coronavirus-and-me-and-dad-erotic-book.html",
    "I just want to make you happy.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/mother-in-law-erotic-book-illustrated.html",
    "I’ve been very bold and need to be punished.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-crush-erotic-book-illustrated.html",
    "Pleasing you is my only purpose in life.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/high-school-experimentation-erotic-book.html",
    "Please fuck me, daddy.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-photo-shoot-erotic-book-illustrated.html",
    "Can I give you a blow job, master?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "Thank you for fucking me.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "If I offered to cook for you in lingerie and heels what would you say?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/black-cock-whore-erotic-book-illustrated.html",
    "I love anal and ass-to-pussy with my boyfriend.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-wife-is-my-fantasy-erotic-book.html",
    "Is it bad that i get turned on even while his parents are in the room?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/strangers-erotic-book-illustrated.html",
    "I want to be as dirty in bed as can be please any tips\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "I've been fucked hardcore every night for the last week and i have enjoyed it\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/girls-domination-erotic-book-illustrated.html",
    "I’m giving him a blow job my mouth is so dirty you have to wash out my mouth with your sex juices\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/babysitter-erotic-book-illustrated.html",
    "Do you like it when I pull your hair during sex?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/gangbang-erotic-book-illustrated.html",
    "Do you like me talking dirty during sex?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-wifes-best-friend-erotic-book.html",
    "Do you like it when I’m aggressive with you in bed?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sons-college-friends-erotic-book.html",
    "Do you like it when I kiss you?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-aunt-erotic-book-illustrated.html",
    "What color underwear are you wearing?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sex-in-paris-erotic-book-illustrated.html",
    "What kinds of clothes do you like me to wear?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/soccer-mom-erotic-book-illustrated.html",
    "Do you like being on top?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/coronavirus-and-me-and-dad-erotic-book.html",
    "What’s the naughtiest, dirtiest thing that you’ve ever done with a girl?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/mother-in-law-erotic-book-illustrated.html",
    "If you could only have sex in one position for the rest of your life, what would it be? \nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-crush-erotic-book-illustrated.html",
    "If you could only choose between getting blowjobs for the rest of your life or having sex, what would you choose?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/high-school-experimentation-erotic-book.html",
    "What would you say if I asked you to go down on me right now?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-photo-shoot-erotic-book-illustrated.html",
    "Do you prefer my left boob or my right boob?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "Are you a tits or ass guy?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "What is your least favorite sex position?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/black-cock-whore-erotic-book-illustrated.html",
    "What’s your record for the number of times you’ve masturbated in a single day?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-wife-is-my-fantasy-erotic-book.html",
    "Have you ever had phone sex?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/strangers-erotic-book-illustrated.html",
    "Have you ever tried BDSM or Dominance/Submission (D/S) play? Interested in BDSM?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "Do you own any sex toys?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/girls-domination-erotic-book-illustrated.html",
    "What’s the most sensitive part of your body?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/babysitter-erotic-book-illustrated.html",
    "What is one fantasy that you always wanted to try?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/gangbang-erotic-book-illustrated.html",
    "When’s the last time you watched porn?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-wifes-best-friend-erotic-book.html",
    "When’s the last time you masturbated?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sons-college-friends-erotic-book.html",
    "If you could be 4 inches taller or have an extra 4 inches in length and girth to your penis, what would you choose?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-aunt-erotic-book-illustrated.html",
    "Have you ever had sex outside?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sex-in-paris-erotic-book-illustrated.html",
    "Has a girl ever used a strapon on you?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/soccer-mom-erotic-book-illustrated.html",
    "If we were in a sex shop right now, what three things would you buy for me?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/coronavirus-and-me-and-dad-erotic-book.html",
    "Are you an oral sex guy, anal sex guy or regular sex guy?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/mother-in-law-erotic-book-illustrated.html",
    "What age were you the first time you jacked off?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-crush-erotic-book-illustrated.html",
    "Have your parents ever caught you jerking off?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/high-school-experimentation-erotic-book.html",
    "Have you ever kissed a guy?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-photo-shoot-erotic-book-illustrated.html",
    "Have you ever given a facial at the end of oral sex?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "Shaved or landing strip, which do you prefer?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "If I could only work as either a pornstar or stripper, which would you prefer me to do?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/black-cock-whore-erotic-book-illustrated.html",
    "Would you prefer me to spit or swallow?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-wife-is-my-fantasy-erotic-book.html",
    "Do you have any fantasies that embarrass you?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/strangers-erotic-book-illustrated.html",
    "Have you ever had sex with someone that couldn’t speak English?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "Have you ever had sex with more than one person at the same time?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/girls-domination-erotic-book-illustrated.html",
    "What’s the craziest sexual thing you’ve ever done?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/babysitter-erotic-book-illustrated.html",
    "Have you ever tried anilingus?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/gangbang-erotic-book-illustrated.html",
    "How many people have you kissed in your life?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-wifes-best-friend-erotic-book.html",
    "Have you ever been with a girl bigger than you?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sons-college-friends-erotic-book.html",
    "When is the last time you’ve been to a strip club?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-aunt-erotic-book-illustrated.html",
    "Have you ever tried skinny dipping?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sex-in-paris-erotic-book-illustrated.html",
    "What age were you when you lost your virginity?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/soccer-mom-erotic-book-illustrated.html",
    "Have you ever wanted to dominate me in the bedroom?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/coronavirus-and-me-and-dad-erotic-book.html",
    "What’s the roughest sex you’ve ever had?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/mother-in-law-erotic-book-illustrated.html",
    "Tell me about the kinkiest sex you’ve ever had? \nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-crush-erotic-book-illustrated.html",
    "Have you ever had a threesome? Have you ever wanted to try one?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/high-school-experimentation-erotic-book.html",
    "Have you ever fantasized about being a sex slave? What about me being your sex slave?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-photo-shoot-erotic-book-illustrated.html",
    "Would you find it hot to see me kiss a girl?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "Do you want to watch porn with me?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "Would you find it hot if I made you wear a butt plug?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/black-cock-whore-erotic-book-illustrated.html",
    "What’s the quickest you’ve ever blown your load?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-wife-is-my-fantasy-erotic-book.html",
    "Do you want to watch me masturbate?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/strangers-erotic-book-illustrated.html",
    "Can I watch you masturbate?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "Can I sit on your face?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/girls-domination-erotic-book-illustrated.html",
    "Have you ever peed on someone?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/babysitter-erotic-book-illustrated.html",
    "Have you ever cried during sex?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/gangbang-erotic-book-illustrated.html",
    "Would you ever cheat on someone if the sex was bad?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-wifes-best-friend-erotic-book.html",
    "When’s the last time you masturbated about me?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sons-college-friends-erotic-book.html",
    "Have you ever wanted to try something with me, but were afraid to ask?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-aunt-erotic-book-illustrated.html",
    "If I asked you to slap me, what would you say?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sex-in-paris-erotic-book-illustrated.html",
    "Have you ever had a massage with a happy ending?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/soccer-mom-erotic-book-illustrated.html",
    "What’s worse, foreplay that lasts forever or no foreplay at all?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/coronavirus-and-me-and-dad-erotic-book.html",
    "Do you think tattoos make girls look more or less sexy?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/mother-in-law-erotic-book-illustrated.html",
    "Have you ever masturbated while on the phone or while texting someone?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-crush-erotic-book-illustrated.html",
    "Have you ever had a one stand? How many?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/high-school-experimentation-erotic-book.html",
    "Do you like it when I talk dirty? \nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-photo-shoot-erotic-book-illustrated.html",
    "What’s the sexiest thing a woman has ever done for you?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-son-ans-myself-erotic-book.html",
    "Hearing you groan, moan and shout when you cum is so fucking satisfying.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/asian-daughters-erotic-book-illustrated.html",
    "Make me cum with your tongue.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/black-cock-whore-erotic-book-illustrated.html",
    "Tonight is all about me, so get down on your knees and put that tongue of yours to work.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-wife-is-my-fantasy-erotic-book.html",
    "There is something so damn hot when you pin me down by my wrists.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/strangers-erotic-book-illustrated.html",
    "Feeling your seed drip down my leg was the perfect reminder of this morning.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/stepmothers-revenge-erotic-book.html",
    "I’m going to need your services tonight, boy.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/girls-domination-erotic-book-illustrated.html",
    "I’ve never been fucked like that before.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/babysitter-erotic-book-illustrated.html",
    "Did you take a course on how to make me cum?\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/gangbang-erotic-book-illustrated.html",
    "Tonight is all about making you cry with pleasure.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/the-wifes-best-friend-erotic-book.html",
    "I dreamt about you last night and woke up dripping wet, which was nice.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sons-college-friends-erotic-book.html",
    "I love when you’re rough with me.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/my-aunt-erotic-book-illustrated.html",
    "I’ve been a bad girl and deserve a spanking.\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/sex-in-paris-erotic-book-illustrated.html",
    "Take your clothes off and get on your hands and knees. Right now!\nBuy this erotic book(high quality pictures):\nhttps://booksforsex.blogspot.com/2020/12/soccer-mom-erotic-book-illustrated.html"
]

item = random.choice(tweet)
